modLoader="javafml"
loaderVersion="[47,)"
license="All Rights Reserved"

[[mods]]
modId="lowlands_clothing"
version="1.0.0"
displayName="Lowlands Clothing"
displayURL="https://mcreator.net"
credits="Created using mod maker MCreator - https://mcreator.net/about"
authors="anton, MCreator"

# Start of user code block mod configuration
# End of user code block mod configuration

[[dependencies.lowlands_clothing]]
    modId="minecraft"
    mandatory=true
    versionRange="[1.20.1]"
    ordering="AFTER"
    side="BOTH"




# Start of user code block dependencies configuration
# End of user code block dependencies configuration